### ISSUE TITLE
Should win bc 5th capture is available for blacks

### ISSUE THREAD

**Issue by Tonio2** [Tonio2/Gomoku#76]
99,89,7A,88,8A,7B,6A,5A,A8,9A,87,B7,89,88,8B,98,78,67,89,88,A9,A7,69,AA,A8,6B,5B,6B,BA,C7,7C,49,79,58,76,38,27,D7,E7,B5,97,9A,6D,7B,68,3A,2B,3B,39,3D

**Comment by amasson42** [comment]
Caused by edge case of gap three.
When a blocked two is part of a gap three, it does no longer count as a closed two structure in the cached count.

Not we also check if we don't have closed three.
